[program:revesta-worker]
process_name=%(program_name)s_%(process_num)02d
command=/usr/bin/php /var/www/revesta/artisan queue:work --sleep=3 --tries=3 --memory=512 --queue=default,emails
user=www-data
numprocs=1
autostart=true
autorestart=true
startsecs=5
redirect_stderr=true
stdout_logfile=/var/log/revesta/worker.log
stderr_logfile=/var/log/revesta/worker.err.log